spring.application.name=expense-tracking

spring.datasource.url=jdbc:postgresql://localhost:5432/productivity_db
spring.datasource.username=postgres
spring.datasource.password=Haneesh_485psql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
# Use a strong, secure 256-bit+ HMAC secret key
blaze.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
blaze.app.jwtExpirationMs=86400000
